<?php

use Illuminate\Database\Seeder;

class JobAssignmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('job_assignments')->delete();
        
        \DB::table('job_assignments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'application_id' => 'DPRAPPLICATION00002',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00001',
                'job_application_status' => 'Site Suitable',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00006',
                'created_at' => '2018-12-12 11:20:27',
                'updated_at' => '2018-12-13 19:32:37',
            ),
            1 => 
            array (
                'id' => 2,
                'application_id' => 'DPRAPPLICATION00003',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00001',
                'job_application_status' => 'ATC Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00003',
                'created_at' => '2018-12-13 20:41:48',
                'updated_at' => '2018-12-21 15:00:28',
            ),
            2 => 
            array (
                'id' => 3,
                'application_id' => 'DPRAPPLICATION00004',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00002',
                'job_application_status' => 'Site Suitable',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00006',
                'created_at' => '2018-12-23 14:00:45',
                'updated_at' => '2018-12-24 21:57:59',
            ),
            3 => 
            array (
                'id' => 4,
                'application_id' => 'DPRAPPLICATION00006',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Site Suitable',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00006',
                'created_at' => '2019-01-19 22:35:04',
                'updated_at' => '2019-02-03 09:40:03',
            ),
            4 => 
            array (
                'id' => 5,
                'application_id' => 'DPRAPPLICATION00007',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Assigned',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-01-20 01:27:26',
                'updated_at' => '2019-01-20 01:27:26',
            ),
            5 => 
            array (
                'id' => 6,
                'application_id' => 'DPRAPPLICATION00010',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00005',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Site Suitable',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00006',
                'created_at' => '2019-02-02 21:30:23',
                'updated_at' => '2019-02-03 10:36:03',
            ),
            6 => 
            array (
                'id' => 7,
                'application_id' => 'DPRAPPLICATION00011',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Site Suitable',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00006',
                'created_at' => '2019-02-03 10:25:48',
                'updated_at' => '2019-02-06 20:14:25',
            ),
            7 => 
            array (
                'id' => 8,
                'application_id' => 'DPRAPPLICATION00012',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00005',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00004',
                'job_application_status' => 'ATC Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00005',
                'created_at' => '2019-02-03 14:10:50',
                'updated_at' => '2019-02-03 17:15:39',
            ),
            8 => 
            array (
                'id' => 9,
                'application_id' => 'DPRAPPLICATION00013',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00005',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00004',
                'job_application_status' => 'Application Sent to HQ',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-02-03 21:42:43',
                'updated_at' => '2019-02-04 03:25:04',
            ),
            9 => 
            array (
                'id' => 10,
                'application_id' => 'DPRAPPLICATION00015',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00005',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'ATC Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00005',
                'created_at' => '2019-02-04 20:35:29',
                'updated_at' => '2019-02-04 21:01:08',
            ),
            10 => 
            array (
                'id' => 11,
                'application_id' => 'DPRAPPLICATION00016',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'Application Sent to HQ',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-02-04 21:34:30',
                'updated_at' => '2019-02-04 21:37:04',
            ),
            11 => 
            array (
                'id' => 12,
                'application_id' => 'DPRAPPLICATION00017',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'ATC Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00005',
                'created_at' => '2019-02-04 23:46:44',
                'updated_at' => '2019-02-04 23:49:26',
            ),
            12 => 
            array (
                'id' => 13,
                'application_id' => 'DPRAPPLICATION00018',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'Application Sent to HQ',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-02-05 00:34:27',
                'updated_at' => '2019-02-05 00:35:24',
            ),
            13 => 
            array (
                'id' => 14,
                'application_id' => 'DPRAPPLICATION00020',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00001',
                'job_application_status' => 'LTO Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00011',
                'created_at' => '2019-02-05 14:02:39',
                'updated_at' => '2019-03-03 07:05:58',
            ),
            14 => 
            array (
                'id' => 15,
                'application_id' => 'DPRAPPLICATION00005',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Site Suitable',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00006',
                'created_at' => '2019-02-06 20:54:51',
                'updated_at' => '2019-03-09 12:33:15',
            ),
            15 => 
            array (
                'id' => 16,
                'application_id' => 'DPRAPPLICATION00021',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'ATC Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00008',
                'created_at' => '2019-02-06 20:54:58',
                'updated_at' => '2019-02-06 23:54:58',
            ),
            16 => 
            array (
                'id' => 17,
                'application_id' => 'DPRAPPLICATION00023',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'LTO Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00011',
                'created_at' => '2019-02-10 20:47:36',
                'updated_at' => '2019-02-26 20:23:20',
            ),
            17 => 
            array (
                'id' => 18,
                'application_id' => 'DPRAPPLICATION00024',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00004',
                'job_application_status' => 'ATI Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00008',
                'created_at' => '2019-02-11 22:42:09',
                'updated_at' => '2019-02-12 19:24:17',
            ),
            18 => 
            array (
                'id' => 19,
                'application_id' => 'DPRAPPLICATION00025',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00004',
                'job_application_status' => 'Application Sent to HQ',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-02-12 18:23:56',
                'updated_at' => '2019-02-12 20:20:22',
            ),
            19 => 
            array (
                'id' => 20,
                'application_id' => 'DPRAPPLICATION00026',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Started',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-02-13 19:07:37',
                'updated_at' => '2019-02-13 19:22:34',
            ),
            20 => 
            array (
                'id' => 21,
                'application_id' => 'DPRAPPLICATION00027',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00004',
                'job_application_status' => 'ATC Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00008',
                'created_at' => '2019-03-02 19:14:25',
                'updated_at' => '2019-03-02 20:08:11',
            ),
            21 => 
            array (
                'id' => 22,
                'application_id' => 'DPRAPPLICATION00028',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Started',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-03-03 07:31:19',
                'updated_at' => '2019-03-03 07:47:30',
            ),
            22 => 
            array (
                'id' => 24,
                'application_id' => 'DPRAPPLICATION00029',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00004',
                'job_application_status' => 'Pressure Test Succesful',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00007',
                'created_at' => '2019-03-03 21:21:05',
                'updated_at' => '2019-03-05 20:04:49',
            ),
            23 => 
            array (
                'id' => 25,
                'application_id' => 'DPRAPPLICATION00030',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Started',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-03-05 22:08:21',
                'updated_at' => '2019-03-06 01:03:34',
            ),
            24 => 
            array (
                'id' => 26,
                'application_id' => 'DPRAPPLICATION00031',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'ATC Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00008',
                'created_at' => '2019-03-09 13:11:54',
                'updated_at' => '2019-03-09 23:53:49',
            ),
            25 => 
            array (
                'id' => 27,
                'application_id' => 'DPRAPPLICATION00032',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'ATC Issued',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00008',
                'created_at' => '2019-03-17 11:41:47',
                'updated_at' => '2019-03-17 11:43:30',
            ),
            26 => 
            array (
                'id' => 28,
                'application_id' => 'DPRAPPLICATION00033',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => 'DPRCOMP00003',
                'job_application_status' => 'Pressure Test Succesful',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => 'DPRST00007',
                'created_at' => '2019-03-17 11:58:04',
                'updated_at' => '2019-03-17 11:58:45',
            ),
            27 => 
            array (
                'id' => 29,
                'application_id' => 'DPRAPPLICATION00034',
                'assigned_by' => 'DPRST00006',
                'staff_id' => 'DPRST00007',
                'teamlead_id' => NULL,
                'company_id' => NULL,
                'job_application_status' => 'Started',
                'to_zopscon' => NULL,
                'to_ADO' => NULL,
                'to_head_gas' => NULL,
                'approved_by' => NULL,
                'created_at' => '2019-03-18 14:26:40',
                'updated_at' => '2019-03-18 14:27:55',
            ),
        ));
        
        
    }
}